name: Pipeline de Dados TCC

on:
  schedule:
    - cron: '0 0 * * *' # Roda todo dia à meia-noite
  workflow_dispatch: # Permite que rode clicando em um botão para testar

jobs:
  update_database:
    runs-on: self-hosted  #rodar local
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar script de atualização
        env:
          #variáveis do banco local
          DB_HOST: "localhost" 
          DB_NAME: "vuln_db"
          DB_USER: "admin"
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          NVD_KEY: ${{ secrets.NVD_API_KEY }}
        run: python setup.py